-- MySQL Script generated by MySQL Workbench
-- Sun Jan 30 23:02:04 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema OnlineShop
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema OnlineShop
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `OnlineShop` DEFAULT CHARACTER SET utf8 ;
USE `OnlineShop` ;

-- -----------------------------------------------------
-- Table `OnlineShop`.`user_roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OnlineShop`.`user_roles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) CHARACTER SET 'utf8' NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OnlineShop`.`user_statuses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OnlineShop`.`user_statuses` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) CHARACTER SET 'utf8' NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OnlineShop`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OnlineShop`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) CHARACTER SET 'utf8' NULL,
  `surname` VARCHAR(50) CHARACTER SET 'utf8' NULL,
  `mobile` VARCHAR(15) CHARACTER SET 'utf8' NULL,
  `email` VARCHAR(50) CHARACTER SET 'utf8' NOT NULL,
  `passwordEncrypted` VARCHAR(100) CHARACTER SET 'utf8' NOT NULL,
  `registeredAt` DATETIME NOT NULL,
  `lastLoginAt` DATETIME NOT NULL,
  `balance` DOUBLE NOT NULL,
  `statusId` INT NOT NULL,
  `roleId` INT NOT NULL,
  `logInToken` VARCHAR(60) CHARACTER SET 'utf8' NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_user_roles_idx` (`roleId` ASC) VISIBLE,
  INDEX `fk_user_statuses_idx` (`statusId` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `mobile_UNIQUE` (`mobile` ASC) VISIBLE,
  UNIQUE INDEX `logInToken_UNIQUE` (`logInToken` ASC) VISIBLE,
  CONSTRAINT `fk_user_roles_users`
    FOREIGN KEY (`roleId`)
    REFERENCES `OnlineShop`.`user_roles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_statuses_users`
    FOREIGN KEY (`statusId`)
    REFERENCES `OnlineShop`.`user_statuses` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OnlineShop`.`product_categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OnlineShop`.`product_categories` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) CHARACTER SET 'utf8' NOT NULL,
  `imgPath` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE,
  UNIQUE INDEX `imgPath_UNIQUE` (`imgPath` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OnlineShop`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OnlineShop`.`products` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(50) CHARACTER SET 'utf8' NOT NULL,
  `price` DOUBLE NOT NULL,
  `count` INT NOT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NULL,
  `description` TEXT CHARACTER SET 'utf8' NULL,
  `imgPath` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL,
  `categoryId` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_product_categories_idx` (`categoryId` ASC) VISIBLE,
  UNIQUE INDEX `imgPath_UNIQUE` (`imgPath` ASC) VISIBLE,
  UNIQUE INDEX `title_UNIQUE` (`title` ASC) VISIBLE,
  CONSTRAINT `fk_product_categories_products`
    FOREIGN KEY (`categoryId`)
    REFERENCES `OnlineShop`.`product_categories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OnlineShop`.`cart_items`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OnlineShop`.`cart_items` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `userId` INT NOT NULL,
  `productId` INT NOT NULL,
  `count` INT NOT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_products_idx` (`productId` ASC) VISIBLE,
  INDEX `fk_users_idx` (`userId` ASC) VISIBLE,
  CONSTRAINT `fk_products_cart`
    FOREIGN KEY (`productId`)
    REFERENCES `OnlineShop`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_cart`
    FOREIGN KEY (`userId`)
    REFERENCES `OnlineShop`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OnlineShop`.`order_statuses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OnlineShop`.`order_statuses` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) CHARACTER SET 'utf8' NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OnlineShop`.`reviews`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OnlineShop`.`reviews` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `productId` INT NOT NULL,
  `userId` INT NOT NULL,
  `review` TEXT CHARACTER SET 'utf8' NOT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_users_idx` (`userId` ASC) VISIBLE,
  INDEX `fk_products_idx` (`productId` ASC) VISIBLE,
  CONSTRAINT `fk_users_reviews`
    FOREIGN KEY (`userId`)
    REFERENCES `OnlineShop`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_products_reviews`
    FOREIGN KEY (`productId`)
    REFERENCES `OnlineShop`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OnlineShop`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OnlineShop`.`orders` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `userId` INT NOT NULL,
  `statusId` INT NOT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_statuses_orders_idx` (`statusId` ASC) VISIBLE,
  INDEX `fk_users_orders_idx` (`userId` ASC) VISIBLE,
  CONSTRAINT `fk_statuses_orders`
    FOREIGN KEY (`statusId`)
    REFERENCES `OnlineShop`.`order_statuses` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_orders`
    FOREIGN KEY (`userId`)
    REFERENCES `OnlineShop`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OnlineShop`.`order_items`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OnlineShop`.`order_items` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `productId` INT NOT NULL,
  `orderId` INT NOT NULL,
  `count` INT NOT NULL,
  `totalPrice` DOUBLE NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_orders_order_items_idx` (`orderId` ASC) VISIBLE,
  CONSTRAINT `fk_products_order_items`
    FOREIGN KEY (`productId`)
    REFERENCES `OnlineShop`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_orders_order_items`
    FOREIGN KEY (`orderId`)
    REFERENCES `OnlineShop`.`orders` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `OnlineShop`.`user_roles`
-- -----------------------------------------------------
START TRANSACTION;
USE `OnlineShop`;
INSERT INTO `OnlineShop`.`user_roles` (`id`, `name`) VALUES (1, 'USER');
INSERT INTO `OnlineShop`.`user_roles` (`id`, `name`) VALUES (2, 'ADMIN');
INSERT INTO `OnlineShop`.`user_roles` (`id`, `name`) VALUES (3, 'GUEST');

COMMIT;


-- -----------------------------------------------------
-- Data for table `OnlineShop`.`user_statuses`
-- -----------------------------------------------------
START TRANSACTION;
USE `OnlineShop`;
INSERT INTO `OnlineShop`.`user_statuses` (`id`, `name`) VALUES (1, 'VALID');
INSERT INTO `OnlineShop`.`user_statuses` (`id`, `name`) VALUES (2, 'BANNED');

COMMIT;


-- -----------------------------------------------------
-- Data for table `OnlineShop`.`order_statuses`
-- -----------------------------------------------------
START TRANSACTION;
USE `OnlineShop`;
INSERT INTO `OnlineShop`.`order_statuses` (`id`, `name`) VALUES (1, 'ACCEPTED');
INSERT INTO `OnlineShop`.`order_statuses` (`id`, `name`) VALUES (2, 'NOTACCEPTED');

COMMIT;

